name: Publish

on:
  push:
    branches:
      - main
    paths:
      - 'public/**'
      - 'src/**'
      - 'index.html'
      - 'package-lock.json'
      - 'package.json'
      - 'tsconfig.app.json'
      - 'tsconfig.json'
      - 'tsconfig.node.json'
      - 'vite.config.ts'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up the repository
        uses: actions/checkout@v7

      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ vars.NODE_VERSION }}

      - name: Setup Pages
        uses: actions/configure-pages@v6

      - name: Install Dependencies
        run: npm ci

      - name: Build website
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: ./dist

  deploy:
    runs-on: ubuntu-latest
    needs: build

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
